import { ShopItem } from '@/types/rpg';

export const SHOP_CATALOG: ShopItem[] = [
  {
    slug: 'touch-grass-pass',
    name: 'Touch Grass',
    description: 'Official certification confirming you occasionally step outside, breathe oxygen, and observe greenery.',
    category: 'Title',
    price: 150,
    rarity: 'Common',
    icon_name: 'Footprints',
  },
  {
    slug: 'academic-weapon',
    name: 'Academic Weapon',
    description: 'Forged in the fires of back-to-back lectures and relentless study sprints.',
    category: 'Title',
    price: 350,
    rarity: 'Uncommon',
    icon_name: 'GraduationCap',
  },
  {
    slug: 'neon-cyber-frame',
    name: 'Acid Cyber Frame',
    description: 'A luminous neon green perimeter border that frames your character portrait in pure high-tech dominance.',
    category: 'Avatar Frame',
    price: 400,
    rarity: 'Rare',
    icon_name: 'Square',
  },
  {
    slug: 'golden-obsidian-frame',
    name: 'Golden Obsidian Frame',
    description: 'Chiseled obsidian bordered with refined auric gold leaf for serious high-level achievers.',
    category: 'Avatar Frame',
    price: 750,
    rarity: 'Epic',
    icon_name: 'ShieldAlert',
  },
  {
    slug: 'sigma-aura',
    name: 'Sigma Void Aura',
    description: 'A subtle dark-violet particle glow emanating from your character portrait. Pure unspoken focus.',
    category: 'Aura',
    price: 900,
    rarity: 'Epic',
    icon_name: 'Sparkles',
  },
  {
    slug: 'gold-auric-halo',
    name: 'Solar Flare Aura',
    description: 'Radiates intense golden energy particles around your stats and presence banner.',
    category: 'Aura',
    price: 1300,
    rarity: 'Legendary',
    icon_name: 'Sun',
  },
  {
    slug: 'gigachad-jawline',
    name: 'Gigachad Jawline',
    description: 'Chiseled by pure discipline. Sharp enough to effortlessly slice through procrastination.',
    category: 'Flair',
    price: 1000,
    rarity: 'Epic',
    icon_name: 'Zap',
  },
  {
    slug: 'golden-crown',
    name: 'Golden Crown',
    description: 'The supreme emblem of unstoppable daily consistency. Pure prestige.',
    category: 'Flair',
    price: 2000,
    rarity: 'Legendary',
    icon_name: 'Crown',
  },
  {
    slug: 'coffee-elixir',
    name: 'Caffeine Overdrive',
    description: 'Cold-brew concentrate distilled with raw willpower. +100 mental clarity.',
    category: 'Cosmetic',
    price: 200,
    rarity: 'Common',
    icon_name: 'Coffee',
  },
  {
    slug: 'rgb-battlestation',
    name: 'RGB Battlestation',
    description: 'Adds +100 aesthetic to your mental workflow. 240Hz productivity guaranteed.',
    category: 'Cosmetic',
    price: 600,
    rarity: 'Rare',
    icon_name: 'Monitor',
  },
];

export function getShopItemBySlug(slug: string): ShopItem | undefined {
  return SHOP_CATALOG.find((item) => item.slug === slug);
}
